### ISSUE TITLE
market_features.html.jinja template not being installed with pip install

### ISSUE THREAD

**Issue by Havanero** [StefanRatzke/market-features#6]
After  installation of market-features with sudo pip install market-features jinja template is not being copied.

The error is:
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: market_features.html.jinja

**Comment by Havanero** [comment]
Unfortunately the issue still there... jinja template not being copied.

**Comment by nusco** [comment]
Just to rule out mistakes - are we sure that we have the latest release via pip? If you go to the directory where pip installed the library, is the template there?

**Comment by Havanero** [comment]
yes, pip list|grep market-features show the the latest 0.3.3 and inside market-feature installation dir no jinja template just the __init_ files
I'm looking at the setup script again for clues

**Comment by Havanero** [comment]
Stefan - any idea when this will be fixed?

**Comment by Havanero** [comment]
@StefanRatzke - it worked with the new setup.... I've tested on pip install and i can see jinja template
